site_name: GSDC TEM Users Guide
site_url: !ENV READTHEDOCS_CANONICAL_URL

theme:
  name: material
  font:
    text: Nunito Sans
    code: Ubuntu Mono
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_javascript:
  - javascripts/readthedocs.js