# Define the site name
site_name: GSDC TEM Users Guide

# Set the site URL by using a Read the Docs environment variable:
# https://docs.readthedocs.io/en/stable/reference/environment-variables.html
site_url: !ENV READTHEDOCS_CANONICAL_URL

# Set the Material for MkDocs theme
theme:
  name: material
  # https://squidfunk.github.io/mkdocs-material/customization/
  custom_dir: docs/overrides
  font:
    text: Roboto
    code: Ubuntu Mono
  features:
    - announce.dismiss
    - content.action.edit
    - content.action.view
    - content.code.annotate
    - content.code.copy
    - content.tooltips
    - navigation.indexes
    - navigation.sections
    - navigation.tabs
    - navigation.top
    - navigation.tracking
    - search.highlight
    - search.suggest
    - toc.follow

plugins:
  - blog
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'

markdown_extensions:
  - abbr
  - admonition
  - attr_list
  - def_list
  - footnotes
  - md_in_html
  - toc:
      permalink: true
  
# Include extra JS to setup Read the Docs addons integrations
extra_javascript:
  - javascripts/readthedocs.js

nav:
  - Services: index.md
  - Frequently Asked Questions (FAQs) : faqs/faqs.md
  - Changelog: changelog/changelog.md