site_name: GSDC TEM Users Guide
site_url: !ENV READTHEDOCS_CANONICAL_URL

theme:
  name: material
  font:
    text: Nunito Sans
    code: Ubuntu Mono
  palette: 
    - scheme: default
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode
    - scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

plugins:
  - search:
      separator: '[\s\u200b\-_,:!=\[\]()"`/]+|\.(?!\d)|&[lg]t;|(?!\b)(?=[A-Z][a-z])'
  - glightbox

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - attr_list
  - md_in_html
  - pymdownx.blocks.caption
  - tables

extra_javascript:
  - javascripts/readthedocs.js

nav:
  - Services: service/overview.md
  - Resources: service/resources.md
